name = "CQLdriver"
uuid = "9d1c9671-1ee4-5573-9bdf-56d4f028cf50"
version = "0.10.4"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
DataFrames = "0.18, 0.19, 0.20, 0.21"
StructArrays = "0.4"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
