name = "CQLdriver"
uuid = "9d1c9671-1ee4-5573-9bdf-56d4f028cf50"
version = "0.5.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
DataFrames = "0.18, 0.19, 0.20, 0.21"
JuliaDB = "0.13"
StructArrays = "0.4"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
